version: '2'
services:
  tao:
    build:
      context: ./apache
      args:
        - SERVER_NAME
    environment:
      - SERVER_NAME
    links:
      - pgdb
    ports:
      - 80:80
  pgdb:
    build:
      context: ./postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
